repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        additional_dependencies: [
          'flake8-isort',
          'flake8-bugbear',
          'flake8-builtins',
          'flake8-comprehensions',
          'flake8-mutable',
          'flake8-pep3101',
          'flake8-print',
          'flake8-quotes',
          'flake8-logging-format',
          'flake8-debugger',
          'flake8-django',
        ]

  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        args: ['--check']
        exclude: migrations/
